version: '2'
services:
    mapper-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/mapper/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=mapper
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
